# Generated by Django 3.1.5 on 2021-01-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmes',
            name='date_debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='programmes',
            name='date_fin',
            field=models.DateTimeField(),
        ),
    ]
