# Generated by Django 3.1.5 on 2021-02-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recherche",
            name="match_all",
        ),
    ]
