# Generated by Django 3.1.5 on 2021-02-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_remove_recherche_match_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='recherche',
            name='date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
