# Generated by Django 3.1.5 on 2021-03-01 15:55

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0003_recherche_date_creation"),
    ]

    operations = [UnaccentExtension()]
