# Generated by Django 3.1.5 on 2021-03-14 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0004_auto_20210301_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recherche",
            name="max_resultats",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ]
            ),
        ),
    ]
