# Generated by Django 3.1.5 on 2021-02-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0005_auto_20210209_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recherchespecifique',
            name='acteur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='aide_sourd',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='categories',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='critique',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='date_realisation',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='episode',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='note',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='partie',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='pays_realisation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='public',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='realisateur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='scenariste',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='serie',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='titre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='recherchespecifique',
            name='titre_informatif',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
